// All unused swi** would be removed when generating the final fuse code. So no one would never ever see all this garbage (except for
// thoose looking into CompatibilityCode.c - but some day when this is finished there should be only little reason to revisit it).
// Cons of swi2 and swi3 are: they do clutter the C code (and we should aim to have that code as clean as possible - the Inkubator code
// is just an intermediate step that can be littered with useless stuff - who cares), and the counts are redundant informartion (for
// a "zy" it's clear that it is two) ... so all in all `swizw(iMouse)` looks more compact than `swi2(iMouse,x,y)`. But yes, the sheer
// amount of defines for the swixy variant is a big con of the former approach - so let's go for the swi2 version.

#if defined(USE_NATIVE_METAL_IMPL)
  /*| swixx   |*/ #define swixx(A) (A).xx
  /*| swixy   |*/ #define swixy(A) (A).xy
  /*| swixz   |*/ #define swixz(A) (A).xz
  /*| swixw   |*/ #define swixw(A) (A).xw
  /*| swiyx   |*/ #define swiyx(A) (A).yx
  /*| swiyy   |*/ #define swiyy(A) (A).yy
  /*| swiyz   |*/ #define swiyz(A) (A).yz
  /*| swiyw   |*/ #define swiyw(A) (A).yw
  /*| swizx   |*/ #define swizx(A) (A).zx
  /*| swizy   |*/ #define swizy(A) (A).zy
  /*| swizz   |*/ #define swizz(A) (A).zz
  /*| swizw   |*/ #define swizw(A) (A).zw
  /*| swiwx   |*/ #define swiwx(A) (A).wx
  /*| swiwy   |*/ #define swiwy(A) (A).wy
  /*| swiwz   |*/ #define swiwz(A) (A).wz
  /*| swiww   |*/ #define swiww(A) (A).ww
  /*| swixxx  |*/ #define swixxx(A) (A).xxx
  /*| swixxy  |*/ #define swixxy(A) (A).xxy
  /*| swixxz  |*/ #define swixxz(A) (A).xxz
  /*| swixxw  |*/ #define swixxw(A) (A).xxw
  /*| swixyx  |*/ #define swixyx(A) (A).xyx
  /*| swixyy  |*/ #define swixyy(A) (A).xyy
  /*| swixyz  |*/ #define swixyz(A) (A).xyz
  /*| swixyw  |*/ #define swixyw(A) (A).xyw
  /*| swixzx  |*/ #define swixzx(A) (A).xzx
  /*| swixzy  |*/ #define swixzy(A) (A).xzy
  /*| swixzz  |*/ #define swixzz(A) (A).xzz
  /*| swixzw  |*/ #define swixzw(A) (A).xzw
  /*| swixwx  |*/ #define swixwx(A) (A).xwx
  /*| swixwy  |*/ #define swixwy(A) (A).xwy
  /*| swixwz  |*/ #define swixwz(A) (A).xwz
  /*| swixww  |*/ #define swixww(A) (A).xww
  /*| swiyxx  |*/ #define swiyxx(A) (A).yxx
  /*| swiyxy  |*/ #define swiyxy(A) (A).yxy
  /*| swiyxz  |*/ #define swiyxz(A) (A).yxz
  /*| swiyxw  |*/ #define swiyxw(A) (A).yxw
  /*| swiyyx  |*/ #define swiyyx(A) (A).yyx
  /*| swiyyy  |*/ #define swiyyy(A) (A).yyy
  /*| swiyyz  |*/ #define swiyyz(A) (A).yyz
  /*| swiyyw  |*/ #define swiyyw(A) (A).yyw
  /*| swiyzx  |*/ #define swiyzx(A) (A).yzx
  /*| swiyzy  |*/ #define swiyzy(A) (A).yzy
  /*| swiyzz  |*/ #define swiyzz(A) (A).yzz
  /*| swiyzw  |*/ #define swiyzw(A) (A).yzw
  /*| swiywx  |*/ #define swiywx(A) (A).ywx
  /*| swiywy  |*/ #define swiywy(A) (A).ywy
  /*| swiywz  |*/ #define swiywz(A) (A).ywz
  /*| swiyww  |*/ #define swiyww(A) (A).yww
  /*| swizxx  |*/ #define swizxx(A) (A).zxx
  /*| swizxy  |*/ #define swizxy(A) (A).zxy
  /*| swizxz  |*/ #define swizxz(A) (A).zxz
  /*| swizxw  |*/ #define swizxw(A) (A).zxw
  /*| swizyx  |*/ #define swizyx(A) (A).zyx
  /*| swizyy  |*/ #define swizyy(A) (A).zyy
  /*| swizyz  |*/ #define swizyz(A) (A).zyz
  /*| swizyw  |*/ #define swizyw(A) (A).zyw
  /*| swizzx  |*/ #define swizzx(A) (A).zzx
  /*| swizzy  |*/ #define swizzy(A) (A).zzy
  /*| swizzz  |*/ #define swizzz(A) (A).zzz
  /*| swizzw  |*/ #define swizzw(A) (A).zzw
  /*| swizwx  |*/ #define swizwx(A) (A).zwx
  /*| swizwy  |*/ #define swizwy(A) (A).zwy
  /*| swizwz  |*/ #define swizwz(A) (A).zwz
  /*| swizww  |*/ #define swizww(A) (A).zww
  /*| swiwxx  |*/ #define swiwxx(A) (A).wxx
  /*| swiwxy  |*/ #define swiwxy(A) (A).wxy
  /*| swiwxz  |*/ #define swiwxz(A) (A).wxz
  /*| swiwxw  |*/ #define swiwxw(A) (A).wxw
  /*| swiwyx  |*/ #define swiwyx(A) (A).wyx
  /*| swiwyy  |*/ #define swiwyy(A) (A).wyy
  /*| swiwyz  |*/ #define swiwyz(A) (A).wyz
  /*| swiwyw  |*/ #define swiwyw(A) (A).wyw
  /*| swiwzx  |*/ #define swiwzx(A) (A).wzx
  /*| swiwzy  |*/ #define swiwzy(A) (A).wzy
  /*| swiwzz  |*/ #define swiwzz(A) (A).wzz
  /*| swiwzw  |*/ #define swiwzw(A) (A).wzw
  /*| swiwwx  |*/ #define swiwwx(A) (A).wwx
  /*| swiwwy  |*/ #define swiwwy(A) (A).wwy
  /*| swiwwz  |*/ #define swiwwz(A) (A).wwz
  /*| swiwww  |*/ #define swiwww(A) (A).www
  /*| swixxxx |*/ #define swixxxx(A) (A).xxxx
  /*| swixxxy |*/ #define swixxxy(A) (A).xxxy
  /*| swixxxz |*/ #define swixxxz(A) (A).xxxz
  /*| swixxxw |*/ #define swixxxw(A) (A).xxxw
  /*| swixxyx |*/ #define swixxyx(A) (A).xxyx
  /*| swixxyy |*/ #define swixxyy(A) (A).xxyy
  /*| swixxyz |*/ #define swixxyz(A) (A).xxyz
  /*| swixxyw |*/ #define swixxyw(A) (A).xxyw
  /*| swixxzx |*/ #define swixxzx(A) (A).xxzx
  /*| swixxzy |*/ #define swixxzy(A) (A).xxzy
  /*| swixxzz |*/ #define swixxzz(A) (A).xxzz
  /*| swixxzw |*/ #define swixxzw(A) (A).xxzw
  /*| swixxwx |*/ #define swixxwx(A) (A).xxwx
  /*| swixxwy |*/ #define swixxwy(A) (A).xxwy
  /*| swixxwz |*/ #define swixxwz(A) (A).xxwz
  /*| swixxww |*/ #define swixxww(A) (A).xxww
  /*| swixyxx |*/ #define swixyxx(A) (A).xyxx
  /*| swixyxy |*/ #define swixyxy(A) (A).xyxy
  /*| swixyxz |*/ #define swixyxz(A) (A).xyxz
  /*| swixyxw |*/ #define swixyxw(A) (A).xyxw
  /*| swixyyx |*/ #define swixyyx(A) (A).xyyx
  /*| swixyyy |*/ #define swixyyy(A) (A).xyyy
  /*| swixyyz |*/ #define swixyyz(A) (A).xyyz
  /*| swixyyw |*/ #define swixyyw(A) (A).xyyw
  /*| swixyzx |*/ #define swixyzx(A) (A).xyzx
  /*| swixyzy |*/ #define swixyzy(A) (A).xyzy
  /*| swixyzz |*/ #define swixyzz(A) (A).xyzz
  /*| swixyzw |*/ #define swixyzw(A) (A).xyzw
  /*| swixywx |*/ #define swixywx(A) (A).xywx
  /*| swixywy |*/ #define swixywy(A) (A).xywy
  /*| swixywz |*/ #define swixywz(A) (A).xywz
  /*| swixyww |*/ #define swixyww(A) (A).xyww
  /*| swixzxx |*/ #define swixzxx(A) (A).xzxx
  /*| swixzxy |*/ #define swixzxy(A) (A).xzxy
  /*| swixzxz |*/ #define swixzxz(A) (A).xzxz
  /*| swixzxw |*/ #define swixzxw(A) (A).xzxw
  /*| swixzyx |*/ #define swixzyx(A) (A).xzyx
  /*| swixzyy |*/ #define swixzyy(A) (A).xzyy
  /*| swixzyz |*/ #define swixzyz(A) (A).xzyz
  /*| swixzyw |*/ #define swixzyw(A) (A).xzyw
  /*| swixzzx |*/ #define swixzzx(A) (A).xzzx
  /*| swixzzy |*/ #define swixzzy(A) (A).xzzy
  /*| swixzzz |*/ #define swixzzz(A) (A).xzzz
  /*| swixzzw |*/ #define swixzzw(A) (A).xzzw
  /*| swixzwx |*/ #define swixzwx(A) (A).xzwx
  /*| swixzwy |*/ #define swixzwy(A) (A).xzwy
  /*| swixzwz |*/ #define swixzwz(A) (A).xzwz
  /*| swixzww |*/ #define swixzww(A) (A).xzww
  /*| swixwxx |*/ #define swixwxx(A) (A).xwxx
  /*| swixwxy |*/ #define swixwxy(A) (A).xwxy
  /*| swixwxz |*/ #define swixwxz(A) (A).xwxz
  /*| swixwxw |*/ #define swixwxw(A) (A).xwxw
  /*| swixwyx |*/ #define swixwyx(A) (A).xwyx
  /*| swixwyy |*/ #define swixwyy(A) (A).xwyy
  /*| swixwyz |*/ #define swixwyz(A) (A).xwyz
  /*| swixwyw |*/ #define swixwyw(A) (A).xwyw
  /*| swixwzx |*/ #define swixwzx(A) (A).xwzx
  /*| swixwzy |*/ #define swixwzy(A) (A).xwzy
  /*| swixwzz |*/ #define swixwzz(A) (A).xwzz
  /*| swixwzw |*/ #define swixwzw(A) (A).xwzw
  /*| swixwwx |*/ #define swixwwx(A) (A).xwwx
  /*| swixwwy |*/ #define swixwwy(A) (A).xwwy
  /*| swixwwz |*/ #define swixwwz(A) (A).xwwz
  /*| swixwww |*/ #define swixwww(A) (A).xwww
  /*| swiyxxx |*/ #define swiyxxx(A) (A).yxxx
  /*| swiyxxy |*/ #define swiyxxy(A) (A).yxxy
  /*| swiyxxz |*/ #define swiyxxz(A) (A).yxxz
  /*| swiyxxw |*/ #define swiyxxw(A) (A).yxxw
  /*| swiyxyx |*/ #define swiyxyx(A) (A).yxyx
  /*| swiyxyy |*/ #define swiyxyy(A) (A).yxyy
  /*| swiyxyz |*/ #define swiyxyz(A) (A).yxyz
  /*| swiyxyw |*/ #define swiyxyw(A) (A).yxyw
  /*| swiyxzx |*/ #define swiyxzx(A) (A).yxzx
  /*| swiyxzy |*/ #define swiyxzy(A) (A).yxzy
  /*| swiyxzz |*/ #define swiyxzz(A) (A).yxzz
  /*| swiyxzw |*/ #define swiyxzw(A) (A).yxzw
  /*| swiyxwx |*/ #define swiyxwx(A) (A).yxwx
  /*| swiyxwy |*/ #define swiyxwy(A) (A).yxwy
  /*| swiyxwz |*/ #define swiyxwz(A) (A).yxwz
  /*| swiyxww |*/ #define swiyxww(A) (A).yxww
  /*| swiyyxx |*/ #define swiyyxx(A) (A).yyxx
  /*| swiyyxy |*/ #define swiyyxy(A) (A).yyxy
  /*| swiyyxz |*/ #define swiyyxz(A) (A).yyxz
  /*| swiyyxw |*/ #define swiyyxw(A) (A).yyxw
  /*| swiyyyx |*/ #define swiyyyx(A) (A).yyyx
  /*| swiyyyy |*/ #define swiyyyy(A) (A).yyyy
  /*| swiyyyz |*/ #define swiyyyz(A) (A).yyyz
  /*| swiyyyw |*/ #define swiyyyw(A) (A).yyyw
  /*| swiyyzx |*/ #define swiyyzx(A) (A).yyzx
  /*| swiyyzy |*/ #define swiyyzy(A) (A).yyzy
  /*| swiyyzz |*/ #define swiyyzz(A) (A).yyzz
  /*| swiyyzw |*/ #define swiyyzw(A) (A).yyzw
  /*| swiyywx |*/ #define swiyywx(A) (A).yywx
  /*| swiyywy |*/ #define swiyywy(A) (A).yywy
  /*| swiyywz |*/ #define swiyywz(A) (A).yywz
  /*| swiyyww |*/ #define swiyyww(A) (A).yyww
  /*| swiyzxx |*/ #define swiyzxx(A) (A).yzxx
  /*| swiyzxy |*/ #define swiyzxy(A) (A).yzxy
  /*| swiyzxz |*/ #define swiyzxz(A) (A).yzxz
  /*| swiyzxw |*/ #define swiyzxw(A) (A).yzxw
  /*| swiyzyx |*/ #define swiyzyx(A) (A).yzyx
  /*| swiyzyy |*/ #define swiyzyy(A) (A).yzyy
  /*| swiyzyz |*/ #define swiyzyz(A) (A).yzyz
  /*| swiyzyw |*/ #define swiyzyw(A) (A).yzyw
  /*| swiyzzx |*/ #define swiyzzx(A) (A).yzzx
  /*| swiyzzy |*/ #define swiyzzy(A) (A).yzzy
  /*| swiyzzz |*/ #define swiyzzz(A) (A).yzzz
  /*| swiyzzw |*/ #define swiyzzw(A) (A).yzzw
  /*| swiyzwx |*/ #define swiyzwx(A) (A).yzwx
  /*| swiyzwy |*/ #define swiyzwy(A) (A).yzwy
  /*| swiyzwz |*/ #define swiyzwz(A) (A).yzwz
  /*| swiyzww |*/ #define swiyzww(A) (A).yzww
  /*| swiywxx |*/ #define swiywxx(A) (A).ywxx
  /*| swiywxy |*/ #define swiywxy(A) (A).ywxy
  /*| swiywxz |*/ #define swiywxz(A) (A).ywxz
  /*| swiywxw |*/ #define swiywxw(A) (A).ywxw
  /*| swiywyx |*/ #define swiywyx(A) (A).ywyx
  /*| swiywyy |*/ #define swiywyy(A) (A).ywyy
  /*| swiywyz |*/ #define swiywyz(A) (A).ywyz
  /*| swiywyw |*/ #define swiywyw(A) (A).ywyw
  /*| swiywzx |*/ #define swiywzx(A) (A).ywzx
  /*| swiywzy |*/ #define swiywzy(A) (A).ywzy
  /*| swiywzz |*/ #define swiywzz(A) (A).ywzz
  /*| swiywzw |*/ #define swiywzw(A) (A).ywzw
  /*| swiywwx |*/ #define swiywwx(A) (A).ywwx
  /*| swiywwy |*/ #define swiywwy(A) (A).ywwy
  /*| swiywwz |*/ #define swiywwz(A) (A).ywwz
  /*| swiywww |*/ #define swiywww(A) (A).ywww
  /*| swizxxx |*/ #define swizxxx(A) (A).zxxx
  /*| swizxxy |*/ #define swizxxy(A) (A).zxxy
  /*| swizxxz |*/ #define swizxxz(A) (A).zxxz
  /*| swizxxw |*/ #define swizxxw(A) (A).zxxw
  /*| swizxyx |*/ #define swizxyx(A) (A).zxyx
  /*| swizxyy |*/ #define swizxyy(A) (A).zxyy
  /*| swizxyz |*/ #define swizxyz(A) (A).zxyz
  /*| swizxyw |*/ #define swizxyw(A) (A).zxyw
  /*| swizxzx |*/ #define swizxzx(A) (A).zxzx
  /*| swizxzy |*/ #define swizxzy(A) (A).zxzy
  /*| swizxzz |*/ #define swizxzz(A) (A).zxzz
  /*| swizxzw |*/ #define swizxzw(A) (A).zxzw
  /*| swizxwx |*/ #define swizxwx(A) (A).zxwx
  /*| swizxwy |*/ #define swizxwy(A) (A).zxwy
  /*| swizxwz |*/ #define swizxwz(A) (A).zxwz
  /*| swizxww |*/ #define swizxww(A) (A).zxww
  /*| swizyxx |*/ #define swizyxx(A) (A).zyxx
  /*| swizyxy |*/ #define swizyxy(A) (A).zyxy
  /*| swizyxz |*/ #define swizyxz(A) (A).zyxz
  /*| swizyxw |*/ #define swizyxw(A) (A).zyxw
  /*| swizyyx |*/ #define swizyyx(A) (A).zyyx
  /*| swizyyy |*/ #define swizyyy(A) (A).zyyy
  /*| swizyyz |*/ #define swizyyz(A) (A).zyyz
  /*| swizyyw |*/ #define swizyyw(A) (A).zyyw
  /*| swizyzx |*/ #define swizyzx(A) (A).zyzx
  /*| swizyzy |*/ #define swizyzy(A) (A).zyzy
  /*| swizyzz |*/ #define swizyzz(A) (A).zyzz
  /*| swizyzw |*/ #define swizyzw(A) (A).zyzw
  /*| swizywx |*/ #define swizywx(A) (A).zywx
  /*| swizywy |*/ #define swizywy(A) (A).zywy
  /*| swizywz |*/ #define swizywz(A) (A).zywz
  /*| swizyww |*/ #define swizyww(A) (A).zyww
  /*| swizzxx |*/ #define swizzxx(A) (A).zzxx
  /*| swizzxy |*/ #define swizzxy(A) (A).zzxy
  /*| swizzxz |*/ #define swizzxz(A) (A).zzxz
  /*| swizzxw |*/ #define swizzxw(A) (A).zzxw
  /*| swizzyx |*/ #define swizzyx(A) (A).zzyx
  /*| swizzyy |*/ #define swizzyy(A) (A).zzyy
  /*| swizzyz |*/ #define swizzyz(A) (A).zzyz
  /*| swizzyw |*/ #define swizzyw(A) (A).zzyw
  /*| swizzzx |*/ #define swizzzx(A) (A).zzzx
  /*| swizzzy |*/ #define swizzzy(A) (A).zzzy
  /*| swizzzz |*/ #define swizzzz(A) (A).zzzz
  /*| swizzzw |*/ #define swizzzw(A) (A).zzzw
  /*| swizzwx |*/ #define swizzwx(A) (A).zzwx
  /*| swizzwy |*/ #define swizzwy(A) (A).zzwy
  /*| swizzwz |*/ #define swizzwz(A) (A).zzwz
  /*| swizzww |*/ #define swizzww(A) (A).zzww
  /*| swizwxx |*/ #define swizwxx(A) (A).zwxx
  /*| swizwxy |*/ #define swizwxy(A) (A).zwxy
  /*| swizwxz |*/ #define swizwxz(A) (A).zwxz
  /*| swizwxw |*/ #define swizwxw(A) (A).zwxw
  /*| swizwyx |*/ #define swizwyx(A) (A).zwyx
  /*| swizwyy |*/ #define swizwyy(A) (A).zwyy
  /*| swizwyz |*/ #define swizwyz(A) (A).zwyz
  /*| swizwyw |*/ #define swizwyw(A) (A).zwyw
  /*| swizwzx |*/ #define swizwzx(A) (A).zwzx
  /*| swizwzy |*/ #define swizwzy(A) (A).zwzy
  /*| swizwzz |*/ #define swizwzz(A) (A).zwzz
  /*| swizwzw |*/ #define swizwzw(A) (A).zwzw
  /*| swizwwx |*/ #define swizwwx(A) (A).zwwx
  /*| swizwwy |*/ #define swizwwy(A) (A).zwwy
  /*| swizwwz |*/ #define swizwwz(A) (A).zwwz
  /*| swizwww |*/ #define swizwww(A) (A).zwww
  /*| swiwxxx |*/ #define swiwxxx(A) (A).wxxx
  /*| swiwxxy |*/ #define swiwxxy(A) (A).wxxy
  /*| swiwxxz |*/ #define swiwxxz(A) (A).wxxz
  /*| swiwxxw |*/ #define swiwxxw(A) (A).wxxw
  /*| swiwxyx |*/ #define swiwxyx(A) (A).wxyx
  /*| swiwxyy |*/ #define swiwxyy(A) (A).wxyy
  /*| swiwxyz |*/ #define swiwxyz(A) (A).wxyz
  /*| swiwxyw |*/ #define swiwxyw(A) (A).wxyw
  /*| swiwxzx |*/ #define swiwxzx(A) (A).wxzx
  /*| swiwxzy |*/ #define swiwxzy(A) (A).wxzy
  /*| swiwxzz |*/ #define swiwxzz(A) (A).wxzz
  /*| swiwxzw |*/ #define swiwxzw(A) (A).wxzw
  /*| swiwxwx |*/ #define swiwxwx(A) (A).wxwx
  /*| swiwxwy |*/ #define swiwxwy(A) (A).wxwy
  /*| swiwxwz |*/ #define swiwxwz(A) (A).wxwz
  /*| swiwxww |*/ #define swiwxww(A) (A).wxww
  /*| swiwyxx |*/ #define swiwyxx(A) (A).wyxx
  /*| swiwyxy |*/ #define swiwyxy(A) (A).wyxy
  /*| swiwyxz |*/ #define swiwyxz(A) (A).wyxz
  /*| swiwyxw |*/ #define swiwyxw(A) (A).wyxw
  /*| swiwyyx |*/ #define swiwyyx(A) (A).wyyx
  /*| swiwyyy |*/ #define swiwyyy(A) (A).wyyy
  /*| swiwyyz |*/ #define swiwyyz(A) (A).wyyz
  /*| swiwyyw |*/ #define swiwyyw(A) (A).wyyw
  /*| swiwyzx |*/ #define swiwyzx(A) (A).wyzx
  /*| swiwyzy |*/ #define swiwyzy(A) (A).wyzy
  /*| swiwyzz |*/ #define swiwyzz(A) (A).wyzz
  /*| swiwyzw |*/ #define swiwyzw(A) (A).wyzw
  /*| swiwywx |*/ #define swiwywx(A) (A).wywx
  /*| swiwywy |*/ #define swiwywy(A) (A).wywy
  /*| swiwywz |*/ #define swiwywz(A) (A).wywz
  /*| swiwyww |*/ #define swiwyww(A) (A).wyww
  /*| swiwzxx |*/ #define swiwzxx(A) (A).wzxx
  /*| swiwzxy |*/ #define swiwzxy(A) (A).wzxy
  /*| swiwzxz |*/ #define swiwzxz(A) (A).wzxz
  /*| swiwzxw |*/ #define swiwzxw(A) (A).wzxw
  /*| swiwzyx |*/ #define swiwzyx(A) (A).wzyx
  /*| swiwzyy |*/ #define swiwzyy(A) (A).wzyy
  /*| swiwzyz |*/ #define swiwzyz(A) (A).wzyz
  /*| swiwzyw |*/ #define swiwzyw(A) (A).wzyw
  /*| swiwzzx |*/ #define swiwzzx(A) (A).wzzx
  /*| swiwzzy |*/ #define swiwzzy(A) (A).wzzy
  /*| swiwzzz |*/ #define swiwzzz(A) (A).wzzz
  /*| swiwzzw |*/ #define swiwzzw(A) (A).wzzw
  /*| swiwzwx |*/ #define swiwzwx(A) (A).wzwx
  /*| swiwzwy |*/ #define swiwzwy(A) (A).wzwy
  /*| swiwzwz |*/ #define swiwzwz(A) (A).wzwz
  /*| swiwzww |*/ #define swiwzww(A) (A).wzww
  /*| swiwwxx |*/ #define swiwwxx(A) (A).wwxx
  /*| swiwwxy |*/ #define swiwwxy(A) (A).wwxy
  /*| swiwwxz |*/ #define swiwwxz(A) (A).wwxz
  /*| swiwwxw |*/ #define swiwwxw(A) (A).wwxw
  /*| swiwwyx |*/ #define swiwwyx(A) (A).wwyx
  /*| swiwwyy |*/ #define swiwwyy(A) (A).wwyy
  /*| swiwwyz |*/ #define swiwwyz(A) (A).wwyz
  /*| swiwwyw |*/ #define swiwwyw(A) (A).wwyw
  /*| swiwwzx |*/ #define swiwwzx(A) (A).wwzx
  /*| swiwwzy |*/ #define swiwwzy(A) (A).wwzy
  /*| swiwwzz |*/ #define swiwwzz(A) (A).wwzz
  /*| swiwwzw |*/ #define swiwwzw(A) (A).wwzw
  /*| swiwwwx |*/ #define swiwwwx(A) (A).wwwx
  /*| swiwwwy |*/ #define swiwwwy(A) (A).wwwy
  /*| swiwwwz |*/ #define swiwwwz(A) (A).wwwz
  /*| swiwwww |*/ #define swiwwww(A) (A).wwww
#else
  /*| swixx   |*/ #define swixx(A) to_float2((A).x,(A).x)
  /*| swixy   |*/ #define swixy(A) to_float2((A).x,(A).y)
  /*| swixz   |*/ #define swixz(A) to_float2((A).x,(A).z)
  /*| swixw   |*/ #define swixw(A) to_float2((A).x,(A).w)
  /*| swiyx   |*/ #define swiyx(A) to_float2((A).y,(A).x)
  /*| swiyy   |*/ #define swiyy(A) to_float2((A).y,(A).y)
  /*| swiyz   |*/ #define swiyz(A) to_float2((A).y,(A).z)
  /*| swiyw   |*/ #define swiyw(A) to_float2((A).y,(A).w)
  /*| swizx   |*/ #define swizx(A) to_float2((A).z,(A).x)
  /*| swizy   |*/ #define swizy(A) to_float2((A).z,(A).y)
  /*| swizz   |*/ #define swizz(A) to_float2((A).z,(A).z)
  /*| swizw   |*/ #define swizw(A) to_float2((A).z,(A).w)
  /*| swiwx   |*/ #define swiwx(A) to_float2((A).w,(A).x)
  /*| swiwy   |*/ #define swiwy(A) to_float2((A).w,(A).y)
  /*| swiwz   |*/ #define swiwz(A) to_float2((A).w,(A).z)
  /*| swiww   |*/ #define swiww(A) to_float2((A).w,(A).w)
  /*| swixxx  |*/ #define swixxx(A) to_float3((A).x,(A).x,(A).x)
  /*| swixxy  |*/ #define swixxy(A) to_float3((A).x,(A).x,(A).y)
  /*| swixxz  |*/ #define swixxz(A) to_float3((A).x,(A).x,(A).z)
  /*| swixxw  |*/ #define swixxw(A) to_float3((A).x,(A).x,(A).w)
  /*| swixyx  |*/ #define swixyx(A) to_float3((A).x,(A).y,(A).x)
  /*| swixyy  |*/ #define swixyy(A) to_float3((A).x,(A).y,(A).y)
  /*| swixyz  |*/ #define swixyz(A) to_float3((A).x,(A).y,(A).z)
  /*| swixyw  |*/ #define swixyw(A) to_float3((A).x,(A).y,(A).w)
  /*| swixzx  |*/ #define swixzx(A) to_float3((A).x,(A).z,(A).x)
  /*| swixzy  |*/ #define swixzy(A) to_float3((A).x,(A).z,(A).y)
  /*| swixzz  |*/ #define swixzz(A) to_float3((A).x,(A).z,(A).z)
  /*| swixzw  |*/ #define swixzw(A) to_float3((A).x,(A).z,(A).w)
  /*| swixwx  |*/ #define swixwx(A) to_float3((A).x,(A).w,(A).x)
  /*| swixwy  |*/ #define swixwy(A) to_float3((A).x,(A).w,(A).y)
  /*| swixwz  |*/ #define swixwz(A) to_float3((A).x,(A).w,(A).z)
  /*| swixww  |*/ #define swixww(A) to_float3((A).x,(A).w,(A).w)
  /*| swiyxx  |*/ #define swiyxx(A) to_float3((A).y,(A).x,(A).x)
  /*| swiyxy  |*/ #define swiyxy(A) to_float3((A).y,(A).x,(A).y)
  /*| swiyxz  |*/ #define swiyxz(A) to_float3((A).y,(A).x,(A).z)
  /*| swiyxw  |*/ #define swiyxw(A) to_float3((A).y,(A).x,(A).w)
  /*| swiyyx  |*/ #define swiyyx(A) to_float3((A).y,(A).y,(A).x)
  /*| swiyyy  |*/ #define swiyyy(A) to_float3((A).y,(A).y,(A).y)
  /*| swiyyz  |*/ #define swiyyz(A) to_float3((A).y,(A).y,(A).z)
  /*| swiyyw  |*/ #define swiyyw(A) to_float3((A).y,(A).y,(A).w)
  /*| swiyzx  |*/ #define swiyzx(A) to_float3((A).y,(A).z,(A).x)
  /*| swiyzy  |*/ #define swiyzy(A) to_float3((A).y,(A).z,(A).y)
  /*| swiyzz  |*/ #define swiyzz(A) to_float3((A).y,(A).z,(A).z)
  /*| swiyzw  |*/ #define swiyzw(A) to_float3((A).y,(A).z,(A).w)
  /*| swiywx  |*/ #define swiywx(A) to_float3((A).y,(A).w,(A).x)
  /*| swiywy  |*/ #define swiywy(A) to_float3((A).y,(A).w,(A).y)
  /*| swiywz  |*/ #define swiywz(A) to_float3((A).y,(A).w,(A).z)
  /*| swiyww  |*/ #define swiyww(A) to_float3((A).y,(A).w,(A).w)
  /*| swizxx  |*/ #define swizxx(A) to_float3((A).z,(A).x,(A).x)
  /*| swizxy  |*/ #define swizxy(A) to_float3((A).z,(A).x,(A).y)
  /*| swizxz  |*/ #define swizxz(A) to_float3((A).z,(A).x,(A).z)
  /*| swizxw  |*/ #define swizxw(A) to_float3((A).z,(A).x,(A).w)
  /*| swizyx  |*/ #define swizyx(A) to_float3((A).z,(A).y,(A).x)
  /*| swizyy  |*/ #define swizyy(A) to_float3((A).z,(A).y,(A).y)
  /*| swizyz  |*/ #define swizyz(A) to_float3((A).z,(A).y,(A).z)
  /*| swizyw  |*/ #define swizyw(A) to_float3((A).z,(A).y,(A).w)
  /*| swizzx  |*/ #define swizzx(A) to_float3((A).z,(A).z,(A).x)
  /*| swizzy  |*/ #define swizzy(A) to_float3((A).z,(A).z,(A).y)
  /*| swizzz  |*/ #define swizzz(A) to_float3((A).z,(A).z,(A).z)
  /*| swizzw  |*/ #define swizzw(A) to_float3((A).z,(A).z,(A).w)
  /*| swizwx  |*/ #define swizwx(A) to_float3((A).z,(A).w,(A).x)
  /*| swizwy  |*/ #define swizwy(A) to_float3((A).z,(A).w,(A).y)
  /*| swizwz  |*/ #define swizwz(A) to_float3((A).z,(A).w,(A).z)
  /*| swizww  |*/ #define swizww(A) to_float3((A).z,(A).w,(A).w)
  /*| swiwxx  |*/ #define swiwxx(A) to_float3((A).w,(A).x,(A).x)
  /*| swiwxy  |*/ #define swiwxy(A) to_float3((A).w,(A).x,(A).y)
  /*| swiwxz  |*/ #define swiwxz(A) to_float3((A).w,(A).x,(A).z)
  /*| swiwxw  |*/ #define swiwxw(A) to_float3((A).w,(A).x,(A).w)
  /*| swiwyx  |*/ #define swiwyx(A) to_float3((A).w,(A).y,(A).x)
  /*| swiwyy  |*/ #define swiwyy(A) to_float3((A).w,(A).y,(A).y)
  /*| swiwyz  |*/ #define swiwyz(A) to_float3((A).w,(A).y,(A).z)
  /*| swiwyw  |*/ #define swiwyw(A) to_float3((A).w,(A).y,(A).w)
  /*| swiwzx  |*/ #define swiwzx(A) to_float3((A).w,(A).z,(A).x)
  /*| swiwzy  |*/ #define swiwzy(A) to_float3((A).w,(A).z,(A).y)
  /*| swiwzz  |*/ #define swiwzz(A) to_float3((A).w,(A).z,(A).z)
  /*| swiwzw  |*/ #define swiwzw(A) to_float3((A).w,(A).z,(A).w)
  /*| swiwwx  |*/ #define swiwwx(A) to_float3((A).w,(A).w,(A).x)
  /*| swiwwy  |*/ #define swiwwy(A) to_float3((A).w,(A).w,(A).y)
  /*| swiwwz  |*/ #define swiwwz(A) to_float3((A).w,(A).w,(A).z)
  /*| swiwww  |*/ #define swiwww(A) to_float3((A).w,(A).w,(A).w)
  /*| swixxxx |*/ #define swixxxx(A) to_float4((A).x,(A).x,(A).x,(A).x)
  /*| swixxxy |*/ #define swixxxy(A) to_float4((A).x,(A).x,(A).x,(A).y)
  /*| swixxxz |*/ #define swixxxz(A) to_float4((A).x,(A).x,(A).x,(A).z)
  /*| swixxxw |*/ #define swixxxw(A) to_float4((A).x,(A).x,(A).x,(A).w)
  /*| swixxyx |*/ #define swixxyx(A) to_float4((A).x,(A).x,(A).y,(A).x)
  /*| swixxyy |*/ #define swixxyy(A) to_float4((A).x,(A).x,(A).y,(A).y)
  /*| swixxyz |*/ #define swixxyz(A) to_float4((A).x,(A).x,(A).y,(A).z)
  /*| swixxyw |*/ #define swixxyw(A) to_float4((A).x,(A).x,(A).y,(A).w)
  /*| swixxzx |*/ #define swixxzx(A) to_float4((A).x,(A).x,(A).z,(A).x)
  /*| swixxzy |*/ #define swixxzy(A) to_float4((A).x,(A).x,(A).z,(A).y)
  /*| swixxzz |*/ #define swixxzz(A) to_float4((A).x,(A).x,(A).z,(A).z)
  /*| swixxzw |*/ #define swixxzw(A) to_float4((A).x,(A).x,(A).z,(A).w)
  /*| swixxwx |*/ #define swixxwx(A) to_float4((A).x,(A).x,(A).w,(A).x)
  /*| swixxwy |*/ #define swixxwy(A) to_float4((A).x,(A).x,(A).w,(A).y)
  /*| swixxwz |*/ #define swixxwz(A) to_float4((A).x,(A).x,(A).w,(A).z)
  /*| swixxww |*/ #define swixxww(A) to_float4((A).x,(A).x,(A).w,(A).w)
  /*| swixyxx |*/ #define swixyxx(A) to_float4((A).x,(A).y,(A).x,(A).x)
  /*| swixyxy |*/ #define swixyxy(A) to_float4((A).x,(A).y,(A).x,(A).y)
  /*| swixyxz |*/ #define swixyxz(A) to_float4((A).x,(A).y,(A).x,(A).z)
  /*| swixyxw |*/ #define swixyxw(A) to_float4((A).x,(A).y,(A).x,(A).w)
  /*| swixyyx |*/ #define swixyyx(A) to_float4((A).x,(A).y,(A).y,(A).x)
  /*| swixyyy |*/ #define swixyyy(A) to_float4((A).x,(A).y,(A).y,(A).y)
  /*| swixyyz |*/ #define swixyyz(A) to_float4((A).x,(A).y,(A).y,(A).z)
  /*| swixyyw |*/ #define swixyyw(A) to_float4((A).x,(A).y,(A).y,(A).w)
  /*| swixyzx |*/ #define swixyzx(A) to_float4((A).x,(A).y,(A).z,(A).x)
  /*| swixyzy |*/ #define swixyzy(A) to_float4((A).x,(A).y,(A).z,(A).y)
  /*| swixyzz |*/ #define swixyzz(A) to_float4((A).x,(A).y,(A).z,(A).z)
  /*| swixyzw |*/ #define swixyzw(A) to_float4((A).x,(A).y,(A).z,(A).w)
  /*| swixywx |*/ #define swixywx(A) to_float4((A).x,(A).y,(A).w,(A).x)
  /*| swixywy |*/ #define swixywy(A) to_float4((A).x,(A).y,(A).w,(A).y)
  /*| swixywz |*/ #define swixywz(A) to_float4((A).x,(A).y,(A).w,(A).z)
  /*| swixyww |*/ #define swixyww(A) to_float4((A).x,(A).y,(A).w,(A).w)
  /*| swixzxx |*/ #define swixzxx(A) to_float4((A).x,(A).z,(A).x,(A).x)
  /*| swixzxy |*/ #define swixzxy(A) to_float4((A).x,(A).z,(A).x,(A).y)
  /*| swixzxz |*/ #define swixzxz(A) to_float4((A).x,(A).z,(A).x,(A).z)
  /*| swixzxw |*/ #define swixzxw(A) to_float4((A).x,(A).z,(A).x,(A).w)
  /*| swixzyx |*/ #define swixzyx(A) to_float4((A).x,(A).z,(A).y,(A).x)
  /*| swixzyy |*/ #define swixzyy(A) to_float4((A).x,(A).z,(A).y,(A).y)
  /*| swixzyz |*/ #define swixzyz(A) to_float4((A).x,(A).z,(A).y,(A).z)
  /*| swixzyw |*/ #define swixzyw(A) to_float4((A).x,(A).z,(A).y,(A).w)
  /*| swixzzx |*/ #define swixzzx(A) to_float4((A).x,(A).z,(A).z,(A).x)
  /*| swixzzy |*/ #define swixzzy(A) to_float4((A).x,(A).z,(A).z,(A).y)
  /*| swixzzz |*/ #define swixzzz(A) to_float4((A).x,(A).z,(A).z,(A).z)
  /*| swixzzw |*/ #define swixzzw(A) to_float4((A).x,(A).z,(A).z,(A).w)
  /*| swixzwx |*/ #define swixzwx(A) to_float4((A).x,(A).z,(A).w,(A).x)
  /*| swixzwy |*/ #define swixzwy(A) to_float4((A).x,(A).z,(A).w,(A).y)
  /*| swixzwz |*/ #define swixzwz(A) to_float4((A).x,(A).z,(A).w,(A).z)
  /*| swixzww |*/ #define swixzww(A) to_float4((A).x,(A).z,(A).w,(A).w)
  /*| swixwxx |*/ #define swixwxx(A) to_float4((A).x,(A).w,(A).x,(A).x)
  /*| swixwxy |*/ #define swixwxy(A) to_float4((A).x,(A).w,(A).x,(A).y)
  /*| swixwxz |*/ #define swixwxz(A) to_float4((A).x,(A).w,(A).x,(A).z)
  /*| swixwxw |*/ #define swixwxw(A) to_float4((A).x,(A).w,(A).x,(A).w)
  /*| swixwyx |*/ #define swixwyx(A) to_float4((A).x,(A).w,(A).y,(A).x)
  /*| swixwyy |*/ #define swixwyy(A) to_float4((A).x,(A).w,(A).y,(A).y)
  /*| swixwyz |*/ #define swixwyz(A) to_float4((A).x,(A).w,(A).y,(A).z)
  /*| swixwyw |*/ #define swixwyw(A) to_float4((A).x,(A).w,(A).y,(A).w)
  /*| swixwzx |*/ #define swixwzx(A) to_float4((A).x,(A).w,(A).z,(A).x)
  /*| swixwzy |*/ #define swixwzy(A) to_float4((A).x,(A).w,(A).z,(A).y)
  /*| swixwzz |*/ #define swixwzz(A) to_float4((A).x,(A).w,(A).z,(A).z)
  /*| swixwzw |*/ #define swixwzw(A) to_float4((A).x,(A).w,(A).z,(A).w)
  /*| swixwwx |*/ #define swixwwx(A) to_float4((A).x,(A).w,(A).w,(A).x)
  /*| swixwwy |*/ #define swixwwy(A) to_float4((A).x,(A).w,(A).w,(A).y)
  /*| swixwwz |*/ #define swixwwz(A) to_float4((A).x,(A).w,(A).w,(A).z)
  /*| swixwww |*/ #define swixwww(A) to_float4((A).x,(A).w,(A).w,(A).w)
  /*| swiyxxx |*/ #define swiyxxx(A) to_float4((A).y,(A).x,(A).x,(A).x)
  /*| swiyxxy |*/ #define swiyxxy(A) to_float4((A).y,(A).x,(A).x,(A).y)
  /*| swiyxxz |*/ #define swiyxxz(A) to_float4((A).y,(A).x,(A).x,(A).z)
  /*| swiyxxw |*/ #define swiyxxw(A) to_float4((A).y,(A).x,(A).x,(A).w)
  /*| swiyxyx |*/ #define swiyxyx(A) to_float4((A).y,(A).x,(A).y,(A).x)
  /*| swiyxyy |*/ #define swiyxyy(A) to_float4((A).y,(A).x,(A).y,(A).y)
  /*| swiyxyz |*/ #define swiyxyz(A) to_float4((A).y,(A).x,(A).y,(A).z)
  /*| swiyxyw |*/ #define swiyxyw(A) to_float4((A).y,(A).x,(A).y,(A).w)
  /*| swiyxzx |*/ #define swiyxzx(A) to_float4((A).y,(A).x,(A).z,(A).x)
  /*| swiyxzy |*/ #define swiyxzy(A) to_float4((A).y,(A).x,(A).z,(A).y)
  /*| swiyxzz |*/ #define swiyxzz(A) to_float4((A).y,(A).x,(A).z,(A).z)
  /*| swiyxzw |*/ #define swiyxzw(A) to_float4((A).y,(A).x,(A).z,(A).w)
  /*| swiyxwx |*/ #define swiyxwx(A) to_float4((A).y,(A).x,(A).w,(A).x)
  /*| swiyxwy |*/ #define swiyxwy(A) to_float4((A).y,(A).x,(A).w,(A).y)
  /*| swiyxwz |*/ #define swiyxwz(A) to_float4((A).y,(A).x,(A).w,(A).z)
  /*| swiyxww |*/ #define swiyxww(A) to_float4((A).y,(A).x,(A).w,(A).w)
  /*| swiyyxx |*/ #define swiyyxx(A) to_float4((A).y,(A).y,(A).x,(A).x)
  /*| swiyyxy |*/ #define swiyyxy(A) to_float4((A).y,(A).y,(A).x,(A).y)
  /*| swiyyxz |*/ #define swiyyxz(A) to_float4((A).y,(A).y,(A).x,(A).z)
  /*| swiyyxw |*/ #define swiyyxw(A) to_float4((A).y,(A).y,(A).x,(A).w)
  /*| swiyyyx |*/ #define swiyyyx(A) to_float4((A).y,(A).y,(A).y,(A).x)
  /*| swiyyyy |*/ #define swiyyyy(A) to_float4((A).y,(A).y,(A).y,(A).y)
  /*| swiyyyz |*/ #define swiyyyz(A) to_float4((A).y,(A).y,(A).y,(A).z)
  /*| swiyyyw |*/ #define swiyyyw(A) to_float4((A).y,(A).y,(A).y,(A).w)
  /*| swiyyzx |*/ #define swiyyzx(A) to_float4((A).y,(A).y,(A).z,(A).x)
  /*| swiyyzy |*/ #define swiyyzy(A) to_float4((A).y,(A).y,(A).z,(A).y)
  /*| swiyyzz |*/ #define swiyyzz(A) to_float4((A).y,(A).y,(A).z,(A).z)
  /*| swiyyzw |*/ #define swiyyzw(A) to_float4((A).y,(A).y,(A).z,(A).w)
  /*| swiyywx |*/ #define swiyywx(A) to_float4((A).y,(A).y,(A).w,(A).x)
  /*| swiyywy |*/ #define swiyywy(A) to_float4((A).y,(A).y,(A).w,(A).y)
  /*| swiyywz |*/ #define swiyywz(A) to_float4((A).y,(A).y,(A).w,(A).z)
  /*| swiyyww |*/ #define swiyyww(A) to_float4((A).y,(A).y,(A).w,(A).w)
  /*| swiyzxx |*/ #define swiyzxx(A) to_float4((A).y,(A).z,(A).x,(A).x)
  /*| swiyzxy |*/ #define swiyzxy(A) to_float4((A).y,(A).z,(A).x,(A).y)
  /*| swiyzxz |*/ #define swiyzxz(A) to_float4((A).y,(A).z,(A).x,(A).z)
  /*| swiyzxw |*/ #define swiyzxw(A) to_float4((A).y,(A).z,(A).x,(A).w)
  /*| swiyzyx |*/ #define swiyzyx(A) to_float4((A).y,(A).z,(A).y,(A).x)
  /*| swiyzyy |*/ #define swiyzyy(A) to_float4((A).y,(A).z,(A).y,(A).y)
  /*| swiyzyz |*/ #define swiyzyz(A) to_float4((A).y,(A).z,(A).y,(A).z)
  /*| swiyzyw |*/ #define swiyzyw(A) to_float4((A).y,(A).z,(A).y,(A).w)
  /*| swiyzzx |*/ #define swiyzzx(A) to_float4((A).y,(A).z,(A).z,(A).x)
  /*| swiyzzy |*/ #define swiyzzy(A) to_float4((A).y,(A).z,(A).z,(A).y)
  /*| swiyzzz |*/ #define swiyzzz(A) to_float4((A).y,(A).z,(A).z,(A).z)
  /*| swiyzzw |*/ #define swiyzzw(A) to_float4((A).y,(A).z,(A).z,(A).w)
  /*| swiyzwx |*/ #define swiyzwx(A) to_float4((A).y,(A).z,(A).w,(A).x)
  /*| swiyzwy |*/ #define swiyzwy(A) to_float4((A).y,(A).z,(A).w,(A).y)
  /*| swiyzwz |*/ #define swiyzwz(A) to_float4((A).y,(A).z,(A).w,(A).z)
  /*| swiyzww |*/ #define swiyzww(A) to_float4((A).y,(A).z,(A).w,(A).w)
  /*| swiywxx |*/ #define swiywxx(A) to_float4((A).y,(A).w,(A).x,(A).x)
  /*| swiywxy |*/ #define swiywxy(A) to_float4((A).y,(A).w,(A).x,(A).y)
  /*| swiywxz |*/ #define swiywxz(A) to_float4((A).y,(A).w,(A).x,(A).z)
  /*| swiywxw |*/ #define swiywxw(A) to_float4((A).y,(A).w,(A).x,(A).w)
  /*| swiywyx |*/ #define swiywyx(A) to_float4((A).y,(A).w,(A).y,(A).x)
  /*| swiywyy |*/ #define swiywyy(A) to_float4((A).y,(A).w,(A).y,(A).y)
  /*| swiywyz |*/ #define swiywyz(A) to_float4((A).y,(A).w,(A).y,(A).z)
  /*| swiywyw |*/ #define swiywyw(A) to_float4((A).y,(A).w,(A).y,(A).w)
  /*| swiywzx |*/ #define swiywzx(A) to_float4((A).y,(A).w,(A).z,(A).x)
  /*| swiywzy |*/ #define swiywzy(A) to_float4((A).y,(A).w,(A).z,(A).y)
  /*| swiywzz |*/ #define swiywzz(A) to_float4((A).y,(A).w,(A).z,(A).z)
  /*| swiywzw |*/ #define swiywzw(A) to_float4((A).y,(A).w,(A).z,(A).w)
  /*| swiywwx |*/ #define swiywwx(A) to_float4((A).y,(A).w,(A).w,(A).x)
  /*| swiywwy |*/ #define swiywwy(A) to_float4((A).y,(A).w,(A).w,(A).y)
  /*| swiywwz |*/ #define swiywwz(A) to_float4((A).y,(A).w,(A).w,(A).z)
  /*| swiywww |*/ #define swiywww(A) to_float4((A).y,(A).w,(A).w,(A).w)
  /*| swizxxx |*/ #define swizxxx(A) to_float4((A).z,(A).x,(A).x,(A).x)
  /*| swizxxy |*/ #define swizxxy(A) to_float4((A).z,(A).x,(A).x,(A).y)
  /*| swizxxz |*/ #define swizxxz(A) to_float4((A).z,(A).x,(A).x,(A).z)
  /*| swizxxw |*/ #define swizxxw(A) to_float4((A).z,(A).x,(A).x,(A).w)
  /*| swizxyx |*/ #define swizxyx(A) to_float4((A).z,(A).x,(A).y,(A).x)
  /*| swizxyy |*/ #define swizxyy(A) to_float4((A).z,(A).x,(A).y,(A).y)
  /*| swizxyz |*/ #define swizxyz(A) to_float4((A).z,(A).x,(A).y,(A).z)
  /*| swizxyw |*/ #define swizxyw(A) to_float4((A).z,(A).x,(A).y,(A).w)
  /*| swizxzx |*/ #define swizxzx(A) to_float4((A).z,(A).x,(A).z,(A).x)
  /*| swizxzy |*/ #define swizxzy(A) to_float4((A).z,(A).x,(A).z,(A).y)
  /*| swizxzz |*/ #define swizxzz(A) to_float4((A).z,(A).x,(A).z,(A).z)
  /*| swizxzw |*/ #define swizxzw(A) to_float4((A).z,(A).x,(A).z,(A).w)
  /*| swizxwx |*/ #define swizxwx(A) to_float4((A).z,(A).x,(A).w,(A).x)
  /*| swizxwy |*/ #define swizxwy(A) to_float4((A).z,(A).x,(A).w,(A).y)
  /*| swizxwz |*/ #define swizxwz(A) to_float4((A).z,(A).x,(A).w,(A).z)
  /*| swizxww |*/ #define swizxww(A) to_float4((A).z,(A).x,(A).w,(A).w)
  /*| swizyxx |*/ #define swizyxx(A) to_float4((A).z,(A).y,(A).x,(A).x)
  /*| swizyxy |*/ #define swizyxy(A) to_float4((A).z,(A).y,(A).x,(A).y)
  /*| swizyxz |*/ #define swizyxz(A) to_float4((A).z,(A).y,(A).x,(A).z)
  /*| swizyxw |*/ #define swizyxw(A) to_float4((A).z,(A).y,(A).x,(A).w)
  /*| swizyyx |*/ #define swizyyx(A) to_float4((A).z,(A).y,(A).y,(A).x)
  /*| swizyyy |*/ #define swizyyy(A) to_float4((A).z,(A).y,(A).y,(A).y)
  /*| swizyyz |*/ #define swizyyz(A) to_float4((A).z,(A).y,(A).y,(A).z)
  /*| swizyyw |*/ #define swizyyw(A) to_float4((A).z,(A).y,(A).y,(A).w)
  /*| swizyzx |*/ #define swizyzx(A) to_float4((A).z,(A).y,(A).z,(A).x)
  /*| swizyzy |*/ #define swizyzy(A) to_float4((A).z,(A).y,(A).z,(A).y)
  /*| swizyzz |*/ #define swizyzz(A) to_float4((A).z,(A).y,(A).z,(A).z)
  /*| swizyzw |*/ #define swizyzw(A) to_float4((A).z,(A).y,(A).z,(A).w)
  /*| swizywx |*/ #define swizywx(A) to_float4((A).z,(A).y,(A).w,(A).x)
  /*| swizywy |*/ #define swizywy(A) to_float4((A).z,(A).y,(A).w,(A).y)
  /*| swizywz |*/ #define swizywz(A) to_float4((A).z,(A).y,(A).w,(A).z)
  /*| swizyww |*/ #define swizyww(A) to_float4((A).z,(A).y,(A).w,(A).w)
  /*| swizzxx |*/ #define swizzxx(A) to_float4((A).z,(A).z,(A).x,(A).x)
  /*| swizzxy |*/ #define swizzxy(A) to_float4((A).z,(A).z,(A).x,(A).y)
  /*| swizzxz |*/ #define swizzxz(A) to_float4((A).z,(A).z,(A).x,(A).z)
  /*| swizzxw |*/ #define swizzxw(A) to_float4((A).z,(A).z,(A).x,(A).w)
  /*| swizzyx |*/ #define swizzyx(A) to_float4((A).z,(A).z,(A).y,(A).x)
  /*| swizzyy |*/ #define swizzyy(A) to_float4((A).z,(A).z,(A).y,(A).y)
  /*| swizzyz |*/ #define swizzyz(A) to_float4((A).z,(A).z,(A).y,(A).z)
  /*| swizzyw |*/ #define swizzyw(A) to_float4((A).z,(A).z,(A).y,(A).w)
  /*| swizzzx |*/ #define swizzzx(A) to_float4((A).z,(A).z,(A).z,(A).x)
  /*| swizzzy |*/ #define swizzzy(A) to_float4((A).z,(A).z,(A).z,(A).y)
  /*| swizzzz |*/ #define swizzzz(A) to_float4((A).z,(A).z,(A).z,(A).z)
  /*| swizzzw |*/ #define swizzzw(A) to_float4((A).z,(A).z,(A).z,(A).w)
  /*| swizzwx |*/ #define swizzwx(A) to_float4((A).z,(A).z,(A).w,(A).x)
  /*| swizzwy |*/ #define swizzwy(A) to_float4((A).z,(A).z,(A).w,(A).y)
  /*| swizzwz |*/ #define swizzwz(A) to_float4((A).z,(A).z,(A).w,(A).z)
  /*| swizzww |*/ #define swizzww(A) to_float4((A).z,(A).z,(A).w,(A).w)
  /*| swizwxx |*/ #define swizwxx(A) to_float4((A).z,(A).w,(A).x,(A).x)
  /*| swizwxy |*/ #define swizwxy(A) to_float4((A).z,(A).w,(A).x,(A).y)
  /*| swizwxz |*/ #define swizwxz(A) to_float4((A).z,(A).w,(A).x,(A).z)
  /*| swizwxw |*/ #define swizwxw(A) to_float4((A).z,(A).w,(A).x,(A).w)
  /*| swizwyx |*/ #define swizwyx(A) to_float4((A).z,(A).w,(A).y,(A).x)
  /*| swizwyy |*/ #define swizwyy(A) to_float4((A).z,(A).w,(A).y,(A).y)
  /*| swizwyz |*/ #define swizwyz(A) to_float4((A).z,(A).w,(A).y,(A).z)
  /*| swizwyw |*/ #define swizwyw(A) to_float4((A).z,(A).w,(A).y,(A).w)
  /*| swizwzx |*/ #define swizwzx(A) to_float4((A).z,(A).w,(A).z,(A).x)
  /*| swizwzy |*/ #define swizwzy(A) to_float4((A).z,(A).w,(A).z,(A).y)
  /*| swizwzz |*/ #define swizwzz(A) to_float4((A).z,(A).w,(A).z,(A).z)
  /*| swizwzw |*/ #define swizwzw(A) to_float4((A).z,(A).w,(A).z,(A).w)
  /*| swizwwx |*/ #define swizwwx(A) to_float4((A).z,(A).w,(A).w,(A).x)
  /*| swizwwy |*/ #define swizwwy(A) to_float4((A).z,(A).w,(A).w,(A).y)
  /*| swizwwz |*/ #define swizwwz(A) to_float4((A).z,(A).w,(A).w,(A).z)
  /*| swizwww |*/ #define swizwww(A) to_float4((A).z,(A).w,(A).w,(A).w)
  /*| swiwxxx |*/ #define swiwxxx(A) to_float4((A).w,(A).x,(A).x,(A).x)
  /*| swiwxxy |*/ #define swiwxxy(A) to_float4((A).w,(A).x,(A).x,(A).y)
  /*| swiwxxz |*/ #define swiwxxz(A) to_float4((A).w,(A).x,(A).x,(A).z)
  /*| swiwxxw |*/ #define swiwxxw(A) to_float4((A).w,(A).x,(A).x,(A).w)
  /*| swiwxyx |*/ #define swiwxyx(A) to_float4((A).w,(A).x,(A).y,(A).x)
  /*| swiwxyy |*/ #define swiwxyy(A) to_float4((A).w,(A).x,(A).y,(A).y)
  /*| swiwxyz |*/ #define swiwxyz(A) to_float4((A).w,(A).x,(A).y,(A).z)
  /*| swiwxyw |*/ #define swiwxyw(A) to_float4((A).w,(A).x,(A).y,(A).w)
  /*| swiwxzx |*/ #define swiwxzx(A) to_float4((A).w,(A).x,(A).z,(A).x)
  /*| swiwxzy |*/ #define swiwxzy(A) to_float4((A).w,(A).x,(A).z,(A).y)
  /*| swiwxzz |*/ #define swiwxzz(A) to_float4((A).w,(A).x,(A).z,(A).z)
  /*| swiwxzw |*/ #define swiwxzw(A) to_float4((A).w,(A).x,(A).z,(A).w)
  /*| swiwxwx |*/ #define swiwxwx(A) to_float4((A).w,(A).x,(A).w,(A).x)
  /*| swiwxwy |*/ #define swiwxwy(A) to_float4((A).w,(A).x,(A).w,(A).y)
  /*| swiwxwz |*/ #define swiwxwz(A) to_float4((A).w,(A).x,(A).w,(A).z)
  /*| swiwxww |*/ #define swiwxww(A) to_float4((A).w,(A).x,(A).w,(A).w)
  /*| swiwyxx |*/ #define swiwyxx(A) to_float4((A).w,(A).y,(A).x,(A).x)
  /*| swiwyxy |*/ #define swiwyxy(A) to_float4((A).w,(A).y,(A).x,(A).y)
  /*| swiwyxz |*/ #define swiwyxz(A) to_float4((A).w,(A).y,(A).x,(A).z)
  /*| swiwyxw |*/ #define swiwyxw(A) to_float4((A).w,(A).y,(A).x,(A).w)
  /*| swiwyyx |*/ #define swiwyyx(A) to_float4((A).w,(A).y,(A).y,(A).x)
  /*| swiwyyy |*/ #define swiwyyy(A) to_float4((A).w,(A).y,(A).y,(A).y)
  /*| swiwyyz |*/ #define swiwyyz(A) to_float4((A).w,(A).y,(A).y,(A).z)
  /*| swiwyyw |*/ #define swiwyyw(A) to_float4((A).w,(A).y,(A).y,(A).w)
  /*| swiwyzx |*/ #define swiwyzx(A) to_float4((A).w,(A).y,(A).z,(A).x)
  /*| swiwyzy |*/ #define swiwyzy(A) to_float4((A).w,(A).y,(A).z,(A).y)
  /*| swiwyzz |*/ #define swiwyzz(A) to_float4((A).w,(A).y,(A).z,(A).z)
  /*| swiwyzw |*/ #define swiwyzw(A) to_float4((A).w,(A).y,(A).z,(A).w)
  /*| swiwywx |*/ #define swiwywx(A) to_float4((A).w,(A).y,(A).w,(A).x)
  /*| swiwywy |*/ #define swiwywy(A) to_float4((A).w,(A).y,(A).w,(A).y)
  /*| swiwywz |*/ #define swiwywz(A) to_float4((A).w,(A).y,(A).w,(A).z)
  /*| swiwyww |*/ #define swiwyww(A) to_float4((A).w,(A).y,(A).w,(A).w)
  /*| swiwzxx |*/ #define swiwzxx(A) to_float4((A).w,(A).z,(A).x,(A).x)
  /*| swiwzxy |*/ #define swiwzxy(A) to_float4((A).w,(A).z,(A).x,(A).y)
  /*| swiwzxz |*/ #define swiwzxz(A) to_float4((A).w,(A).z,(A).x,(A).z)
  /*| swiwzxw |*/ #define swiwzxw(A) to_float4((A).w,(A).z,(A).x,(A).w)
  /*| swiwzyx |*/ #define swiwzyx(A) to_float4((A).w,(A).z,(A).y,(A).x)
  /*| swiwzyy |*/ #define swiwzyy(A) to_float4((A).w,(A).z,(A).y,(A).y)
  /*| swiwzyz |*/ #define swiwzyz(A) to_float4((A).w,(A).z,(A).y,(A).z)
  /*| swiwzyw |*/ #define swiwzyw(A) to_float4((A).w,(A).z,(A).y,(A).w)
  /*| swiwzzx |*/ #define swiwzzx(A) to_float4((A).w,(A).z,(A).z,(A).x)
  /*| swiwzzy |*/ #define swiwzzy(A) to_float4((A).w,(A).z,(A).z,(A).y)
  /*| swiwzzz |*/ #define swiwzzz(A) to_float4((A).w,(A).z,(A).z,(A).z)
  /*| swiwzzw |*/ #define swiwzzw(A) to_float4((A).w,(A).z,(A).z,(A).w)
  /*| swiwzwx |*/ #define swiwzwx(A) to_float4((A).w,(A).z,(A).w,(A).x)
  /*| swiwzwy |*/ #define swiwzwy(A) to_float4((A).w,(A).z,(A).w,(A).y)
  /*| swiwzwz |*/ #define swiwzwz(A) to_float4((A).w,(A).z,(A).w,(A).z)
  /*| swiwzww |*/ #define swiwzww(A) to_float4((A).w,(A).z,(A).w,(A).w)
  /*| swiwwxx |*/ #define swiwwxx(A) to_float4((A).w,(A).w,(A).x,(A).x)
  /*| swiwwxy |*/ #define swiwwxy(A) to_float4((A).w,(A).w,(A).x,(A).y)
  /*| swiwwxz |*/ #define swiwwxz(A) to_float4((A).w,(A).w,(A).x,(A).z)
  /*| swiwwxw |*/ #define swiwwxw(A) to_float4((A).w,(A).w,(A).x,(A).w)
  /*| swiwwyx |*/ #define swiwwyx(A) to_float4((A).w,(A).w,(A).y,(A).x)
  /*| swiwwyy |*/ #define swiwwyy(A) to_float4((A).w,(A).w,(A).y,(A).y)
  /*| swiwwyz |*/ #define swiwwyz(A) to_float4((A).w,(A).w,(A).y,(A).z)
  /*| swiwwyw |*/ #define swiwwyw(A) to_float4((A).w,(A).w,(A).y,(A).w)
  /*| swiwwzx |*/ #define swiwwzx(A) to_float4((A).w,(A).w,(A).z,(A).x)
  /*| swiwwzy |*/ #define swiwwzy(A) to_float4((A).w,(A).w,(A).z,(A).y)
  /*| swiwwzz |*/ #define swiwwzz(A) to_float4((A).w,(A).w,(A).z,(A).z)
  /*| swiwwzw |*/ #define swiwwzw(A) to_float4((A).w,(A).w,(A).z,(A).w)
  /*| swiwwwx |*/ #define swiwwwx(A) to_float4((A).w,(A).w,(A).w,(A).x)
  /*| swiwwwy |*/ #define swiwwwy(A) to_float4((A).w,(A).w,(A).w,(A).y)
  /*| swiwwwz |*/ #define swiwwwz(A) to_float4((A).w,(A).w,(A).w,(A).z)
  /*| swiwwww |*/ #define swiwwww(A) to_float4((A).w,(A).w,(A).w,(A).w)
#endif
