
// ----------------------------------------------------------------------------------
// - Image                                                                          -
// ----------------------------------------------------------------------------------
// Connect Image 'Texture: Rock Tiles' to iChannel0
// Connect Image 'Texture: Wood' to iChannel1

#define texture(ch,uv) _tex2DVecN(ch, (uv).x, (uv).y, 15)


// TimeWarp @P_Malin
// https://www.shadertoy.com/view/ldl3zn

// Scanline render experiment version here: https://www.shadertoy.com/view/XtsSDH
 
#define ENABLE_REFLECTIONS
#define ENABLE_FOG
#define ENABLE_SPECULAR
#define ENABLE_DIRECTIONAL_LIGHT
//#define ENABLE_MONTE_CARLO

#define kPI  _acosf(0.0f)
#define kTwoPI (kPI * 2.0f)

#ifdef ENABLE_MONTE_CARLO
__TEXTURE2D__ backbuffer;
__DEVICE__ float4 gPixelRandom;
__DEVICE__ float3 gRandomNormal;
 
__DEVICE__ void CalcPixelRandom()
{
    // Nothing special here, just numbers generated by bashing keyboard
    float4 s1 = _sinf(iTime * 3.3422f + swi4(fragCoord,x,x,x,x) * to_float4(324.324234f, 563.324234f, 657.324234f, 764.324234f)) * 543.3423f;
    float4 s2 = _sinf(iTime * 1.3422f + swi4(fragCoord,y,y,y,y) * to_float4(567.324234f, 435.324234f, 432.324234f, 657.324234f)) * 654.5423f;
    gPixelRandom = fract(2142.4f + s1 + s2);
    gRandomNormal = normalize( swi3(gPixelRandom,x,y,z) - 0.5f);
}

__DEVICE__ float GetTime(float iTime)
{
  return 0.0f;
}
#else
__DEVICE__ float GetTime(float iTime)
{
  return iTime;
}
#endif
 
struct C_Ray
{
    float3 vOrigin;
    float3 vDir;
};
 
struct C_HitInfo
{
    float3 vPos;
    float fDistance;
    float3 vObjectId;
};
 
struct C_Material
{
    float3 cAlbedo;
    float fR0;
    float fSmoothness;
    float2 vParam;
};
 
__DEVICE__ float3 RotateX( const in float3 vPos, const in float fAngle )
{
    float s = _sinf(fAngle);
    float c = _cosf(fAngle);
   
    float3 vResult = to_float3( vPos.x, c * vPos.y + s * vPos.z, -s * vPos.y + c * vPos.z);
   
    return vResult;
}
 
__DEVICE__ float3 RotateY( const in float3 vPos, const in float fAngle )
{
    float s = _sinf(fAngle);
    float c = _cosf(fAngle);
   
    float3 vResult = to_float3( c * vPos.x + s * vPos.z, vPos.y, -s * vPos.x + c * vPos.z);
   
    return vResult;
}
   
__DEVICE__ float3 RotateZ( const in float3 vPos, const in float fAngle )
{
    float s = _sinf(fAngle);
    float c = _cosf(fAngle);
   
    float3 vResult = to_float3( c * vPos.x + s * vPos.y, -s * vPos.x + c * vPos.y, vPos.z);
   
    return vResult;
}
 
__DEVICE__ float4 DistCombineUnion( const in float4 v1, const in float4 v2 )
{
    //if(v1.x < v2.x) return v1; else return v2;
    return _mix(v1, v2, step(v2.x, v1.x));
}
 
__DEVICE__ float4 DistCombineIntersect( const in float4 v1, const in float4 v2 )
{
    return _mix(v2, v1, step(v2.x,v1.x));
}
 
__DEVICE__ float4 DistCombineSubtract( const in float4 v1, const in float4 v2 )
{
    return DistCombineIntersect(v1, to_float4(-v2.x, v2.y,v2.z,v2.w));
}
 
__DEVICE__ float3 DomainRepeatXZGetTile( const in float3 vPos, const in float2 vRepeat, out float2 *vTile )
{
    float3 vResult = vPos;
    float2 vTilePos = (swi2(vPos,x,z) / vRepeat) + 0.5f;
    *vTile = _floor(vTilePos + 1000.0f);
    swi2S(vResult,x,z, (fract_f2(vTilePos) - 0.5f) * vRepeat);
    return vResult;
}
 
__DEVICE__ float3 DomainRepeatXZ( const in float3 vPos, const in float2 vRepeat )
{
    float3 vResult = vPos;
    float2 vTilePos = (swi2(vPos,x,z) / vRepeat) + 0.5f;
    swi2S(vResult,x,z, (fract(vTilePos) - 0.5f) * vRepeat);
    return vResult;
}
 
__DEVICE__ float3 DomainRepeatY( const in float3 vPos, const in float fSize )
{
    float3 vResult = vPos;
    vResult.y = (fract(vPos.y / fSize + 0.5f) - 0.5f) * fSize;
    return vResult;
}
 
__DEVICE__ float3 DomainRotateSymmetry( const in float3 vPos, const in float fSteps )
{
    float angle = _atan2f( vPos.x, vPos.z );
 
    float fScale = fSteps / (kTwoPI);
    float steppedAngle = (_floor(angle * fScale + 0.5f)) / fScale;
 
    float s = _sinf(-steppedAngle);
    float c = _cosf(-steppedAngle);
 
    float3 vResult = to_float3( c * vPos.x + s * vPos.z,
                                vPos.y,
                                -s * vPos.x + c * vPos.z);
 
    return vResult;
}
 
__DEVICE__ float GetDistanceXYTorus( const in float3 p, const in float r1, const in float r2 )
{
    float2 q = to_float2(length(swi2(p,x,y))-r1,p.z);
    return length(q)-r2;
}
__DEVICE__ float GetDistanceYZTorus( const in float3 p, const in float r1, const in float r2 )
{
    float2 q = to_float2(length(swi2(p,y,z))-r1,p.x);
    return length(q)-r2;
}
__DEVICE__ float GetDistanceCylinderY(const in float3 vPos, const in float r)
{
    return length(swi2(vPos,x,z)) - r;
}
__DEVICE__ float GetDistanceBox( const in float3 vPos, const in float3 vSize )
{
    float3 vDist = (abs_f3(vPos) - vSize);
    return _fmaxf(vDist.x, _fmaxf(vDist.y, vDist.z));
}
 
__DEVICE__ float GetDistanceRoundedBox( const in float3 vPos, const in float3 vSize, float fRadius )
{
  
    float3 vClosest = _fmaxf(_fminf(vPos, vSize), -1.0f*vSize);
    return length(vClosest - vPos) - fRadius;
}
 
__DEVICE__ float GetDistanceWinder( const in float3 vPos )
{
   float fWinderSize = 0.15f;
   float fAngle = _atan2f(vPos.x, vPos.z) + vPos.y * 2.0f;
  
   float fBump = 1.0f + _sinf(fAngle * 10.0f * kPI) * 0.05f;
   return length(vPos + to_float3(0.0f, -1.0f - 0.2f, 0.0f)) * fBump - fWinderSize;  
}

__DEVICE__ float4 GetDistanceClock( const in float3 vPos, float iTime )
{
  const float fRadius = 1.0f;
  const float fThickness = 0.1f;
  const float fInsetRadius = 0.9f;
  const float fInsetDepth = 0.1f;
  float fTorusDist = GetDistanceXYTorus(vPos, 1.0f, fThickness);
  
  float fCylinderDist = length(swi2(vPos,x,y)) - fRadius;
  float fCylinderCap = _fabs(vPos.z) - fThickness;
  fCylinderDist = _fmaxf(fCylinderDist, fCylinderCap);
  float fDist = _fminf(fTorusDist, fCylinderDist);
  
  float fWinderDist = GetDistanceWinder(vPos);
  fDist = _fminf(fDist, fWinderDist);
  float4 vResult = to_float4(fDist, 2.0f, 0.0f, 0.0f);
  
  float fInsetDist = length(swi2(vPos,x,y)) - fInsetRadius;
  float fInsetCap = _fabs(vPos.z - fThickness) - fInsetDepth;
  
  float4 vInsetCapDist = to_float4(fInsetCap, 3.0f, vPos.x, vPos.y);
  float4 vInsetDist = to_float4(fInsetDist, 2.0f, 0.0f, 0.0f);
  
  vInsetDist = DistCombineIntersect(vInsetDist, vInsetCapDist);
  
  vResult = DistCombineSubtract(vResult, vInsetDist);
  
  
  float fHandSeconds = iTime;
  
  fHandSeconds = _floor(fHandSeconds) + (_powf(fract(fHandSeconds), 50.0f));
  float fHandAngle = -fHandSeconds * kPI * 2.0f / 60.0f;
  
  float3 vHandDomain = RotateZ(vPos, fHandAngle);
  float fHandHeight = 0.05f;
  vHandDomain.z -= fThickness - fInsetDepth + fHandHeight;
  float fHandDist = length(swi2(vHandDomain,x,z)) - 0.01f;
  fHandDist = _fmaxf(fHandDist, (_fabs(vHandDomain.y + 0.4f) - 0.4f));
  
  float4 vHandDist = to_float4(fHandDist, 4.0f, 0.0f, 0.0f);
  
  vResult = DistCombineUnion(vResult, vHandDist);
  
  return vResult;
}
 
__DEVICE__ float3 WarpDomain( const in float3 vPos, float iTime )
{
    float3 vResult = vPos + to_float3(0.0f, 0.1f, 0.1f);

    float fUnbend = clamp(_atan2f(vResult.y, vResult.z), 0.0f, kPI * 0.9f);
    vResult = RotateX(vResult, -fUnbend);
     
    float fDroopBlend = _fmaxf(-vResult.y, 0.0f);  
    vResult.y += fDroopBlend * 0.4f;
    vResult.z += _sinf(vResult.x * 4.0f  + vResult.y * 6.0f + GetTime(iTime)) * fDroopBlend * 0.05f;
    return vResult;
}

// result is x=scene distance y=material or object id; zw are material specific parameters (maybe uv co-ordinates)
__DEVICE__ float4 GetDistanceScene( const in float3 vPos, float iTime )
{         
    float4 vResult = to_float4(10000.0f, -1.0f, 0.0f, 0.0f);
                    
    float3 vClockDomain = WarpDomain(vPos + to_float3(0.0f, -0.1f, -0.45f), iTime);
    vClockDomain.y += 0.2f;  
    vResult = DistCombineUnion(vResult, GetDistanceClock(vClockDomain, iTime));
        
    float4 vWallDist1 = to_float4(vPos.z - 0.2f, 1.0f, vPos.x, vPos.y);
    float4 vWallDist2 = to_float4(vPos.y, 1.0f, vPos.x, vPos.z);
    vWallDist1 = DistCombineIntersect(vWallDist1, vWallDist2);
    vResult = DistCombineUnion(vResult, vWallDist1);
             
  
    float4 vFloorDist = to_float4(vPos.y + 2.3f, 5.0f, vPos.x, vPos.z);
    vResult = DistCombineUnion(vResult, vFloorDist);
  
    return vResult;
}
 
__DEVICE__ float3 GetWatchFaceColour( const float2 vUV )
{
  float fRadius = length(vUV);
 
  float fFraction = (_atan2f(vUV.x, -vUV.y) / (kPI * 2.0f)) + (0.5f / 60.0f);
         
  float fTickValue = fFraction * 60.0f;   
  float fTickIndex = _floor(fTickValue);
  float fTickFraction = fract(fTickValue);
               
  float fTickLength = 0.25f;       
  fTickLength += step( fract(fTickIndex / 10.0f), 0.5f / 10.0f ) * 0.1f;
  fTickLength += step( fract(fTickIndex / 5.0f), 0.5f / 5.0f ) * 0.05f;
  
  float fTickWidth = 0.2f;
  float fInTickSegment = step(_fabs(fTickFraction - 0.5f), fTickWidth);
  
  float fInTickRadiusOuter = step(fRadius, 0.8f);
  float fInTickRadiusInner = step(1.0f - fTickLength, fRadius);
  
  // 1.0f if not one of these...
  float fBlend = 1.0f - fInTickSegment * fInTickRadiusOuter * fInTickRadiusInner;
  
  // central dot
  fBlend = fBlend * step(0.025f, fRadius);                                 
  
  return _mix(to_float3_s(0.05f), to_float3_s(0.95f), fBlend);
}
 
__DEVICE__ C_Material GetObjectMaterial( const in float3 vObjId, const in float3 vPos, const in float3 vNormal, __TEXTURE2D__ iChannel0, __TEXTURE2D__ iChannel1 )
{
    C_Material mat;
             
    if(vObjId.x < 1.5f)
    {
      // wall
      mat.fR0 = 0.2f;
      float3 cTextureSample = swi3(texture(iChannel0, swi2(vObjId,y,z)),x,y,z);//.rgb;
      mat.fSmoothness = cTextureSample.x * cTextureSample.z;
      mat.cAlbedo = cTextureSample * cTextureSample;
    }
    else
    if(vObjId.x < 2.5f)
    {
      // silver
      mat.fR0 = 0.95f;
      mat.fSmoothness = 0.9f;
      mat.cAlbedo = to_float3(0.9f, 0.9f, 0.91f);
    }
    else
    if(vObjId.x < 3.5f)
    {
      // clock face
      mat.fR0 = 0.01f;
      mat.fSmoothness = 0.9f;
      mat.cAlbedo = GetWatchFaceColour( swi2(vObjId,y,z) );
    }
    else
    if(vObjId.x < 4.5f)
    {
      // hand
      mat.fR0 = 0.01f;
      mat.fSmoothness = 0.9f;
      mat.cAlbedo = to_float3(0.95f, 0.05f, 0.05f);
    }
    else
    if(vObjId.x < 5.5f)
    {
      // floor
      mat.fR0 = 0.01f;
      float3 cTextureSample = swi3(texture(iChannel1, swi2(vObjId,y,z)),x,y,z);//.rgb;
      mat.cAlbedo = cTextureSample * cTextureSample;
      mat.fSmoothness = cTextureSample.x * cTextureSample.y;
    }
 
    return mat;
}
__DEVICE__ float3 GetLightDirection()
{
    float3 vLightDir = to_float3(1.0f, 2.0f, 1.0f);

    #ifdef ENABLE_MONTE_CARLO       
    vLightDir += gRandomNormal * 0.01f;
    #endif
    return normalize(vLightDir);
}
__DEVICE__ float3 GetLightCol()
{
    return to_float3(1.0f, 0.7f, 0.5f) * 10.0f;
}

__DEVICE__ float3 GetSkyGradient( const in float3 vDir )
{
  float fBlend = vDir.y * 0.5f + 0.5f;
  return _mix(to_float3(0.0f, 0.0f, 0.0f), to_float3(0.25f, 0.5f, 1.0f) * 4.0f, fBlend);
}
 
__DEVICE__ float3 GetAmbientLight(const in float3 vNormal)
{
    return GetSkyGradient(vNormal);
}
 
#define kFogDensity 0.075f
__DEVICE__ void ApplyAtmosphere(inout float3 col, const in C_Ray ray, const in C_HitInfo intersection)
{
    #ifdef ENABLE_FOG
    // fog
    float fFogAmount = _expf(intersection.fDistance * -kFogDensity);
    float3 cFog = GetSkyGradient(ray.vDir);
    col = _mix(cFog, col, fFogAmount);
    #endif
}

__DEVICE__ float3 GetSceneNormal( const in float3 vPos, float iTime )
{
    // tetrahedron normal
    float fDelta = 0.01f;
 
    float3 vOffset1 = to_float3( fDelta, -fDelta, -fDelta);
    float3 vOffset2 = to_float3(-fDelta, -fDelta,  fDelta);
    float3 vOffset3 = to_float3(-fDelta,  fDelta, -fDelta);
    float3 vOffset4 = to_float3( fDelta,  fDelta,  fDelta);
 
    float f1 = GetDistanceScene( vPos + vOffset1, iTime ).x;
    float f2 = GetDistanceScene( vPos + vOffset2, iTime ).x;
    float f3 = GetDistanceScene( vPos + vOffset3, iTime ).x;
    float f4 = GetDistanceScene( vPos + vOffset4, iTime ).x;
 
    float3 vNormal = vOffset1 * f1 + vOffset2 * f2 + vOffset3 * f3 + vOffset4 * f4;
 
    return normalize( vNormal );
}
 
#define kRaymarchEpsilon 0.01f
#define kRaymarchMatIter 20
#define kRaymarchStartDistance 0.01f
// This is an excellent resource on ray marching -> https://iquilezles.org/articles/distfunctions
__DEVICE__ C_HitInfo Raymarch( const in C_Ray ray, C_HitInfo result, const float fMaxDist, const int maxIter, float iTime )
{       
    result.fDistance = kRaymarchStartDistance;
    result.vObjectId.x = 0.0f;
                             
    for(int i=0;i<=kRaymarchMatIter;i++)             
    {
        result.vPos = ray.vOrigin + ray.vDir * result.fDistance;
        float4 vSceneDist = GetDistanceScene( result.vPos, iTime );
        result.vObjectId = swi3(vSceneDist,y,z,w);
 
        // abs allows backward stepping - should only be necessary for non uniform distance functions
        if((_fabs(vSceneDist.x) <= kRaymarchEpsilon) || (result.fDistance >= fMaxDist) || (i > maxIter))
        {
            break;
        }                       
 
        result.fDistance = result.fDistance + vSceneDist.x;   
    }
      
    if(result.fDistance >= fMaxDist)
    {
        result.vPos = ray.vOrigin + ray.vDir * result.fDistance;
        result.vObjectId.x = 0.0f;
        result.fDistance = 1000.0f;
    }
    
  return result;  
}
 
__DEVICE__ float GetShadow( const in float3 vPos, const in float3 vLightDir, const in float fLightDistance, float iTime )
{
    C_Ray shadowRay;
    shadowRay.vDir = vLightDir;
    shadowRay.vOrigin = vPos;
 
    C_HitInfo shadowIntersect;
    shadowIntersect = Raymarch(shadowRay, shadowIntersect, fLightDistance, 32, iTime);
                                                                                                       
    return step(0.0f, shadowIntersect.fDistance) * step(fLightDistance, shadowIntersect.fDistance );         
}
 
// http://en.wikipedia.org/wiki/Schlick's_approximation
__DEVICE__ float Schlick( const in float3 vNormal, const in float3 vView, const in float fR0, const in float fSmoothFactor)
{
    float fDot = dot(vNormal, -1.0f*vView);
    fDot = _fminf(max((1.0f - fDot), 0.0f), 1.0f);
    float fDot2 = fDot * fDot;
    float fDot5 = fDot2 * fDot2 * fDot;
    return fR0 + (1.0f - fR0) * fDot5 * fSmoothFactor;
}
 
__DEVICE__ float GetDiffuseIntensity(const in float3 vLightDir, const in float3 vNormal)
{
    return _fmaxf(0.0f, dot(vLightDir, vNormal));
}
 
__DEVICE__ float GetBlinnPhongIntensity(const in C_Ray ray, const in C_Material mat, const in float3 vLightDir, const in float3 vNormal)
{         
    float3 vHalf = normalize(vLightDir - ray.vDir);
    float fNdotH = _fmaxf(0.0f, dot(vHalf, vNormal));
 
    float fSpecPower = _exp2f(4.0f + 6.0f * mat.fSmoothness);
    float fSpecIntensity = (fSpecPower + 2.0f) * 0.125f;
 
    return _powf(fNdotH, fSpecPower) * fSpecIntensity;
}
 
// use distance field to evaluate ambient occlusion
__DEVICE__ float GetAmbientOcclusion(const in C_Ray ray, const in C_HitInfo intersection, const in float3 vNormal, float iTime)
{
    float3 vPos = intersection.vPos;
     
    float fAmbientOcclusion = 1.0f;
     
    float fDist = 0.0f;
    for(int i=0; i<=5; i++)
    {
        fDist += 0.1f;
 
        float4 vSceneDist = GetDistanceScene(vPos + vNormal * fDist, iTime);
 
        fAmbientOcclusion *= 1.0f - _fmaxf(0.0f, (fDist - vSceneDist.x) * 0.2f / fDist );                                 
    }
     
    return fAmbientOcclusion;
}
 
__DEVICE__ float3 GetObjectLighting(const in C_Ray ray, const in C_HitInfo intersection, const in C_Material material, const in float3 vNormal, const in float3 cReflection, float iTime)
{
    float3 cScene ;
   
    float3 vSpecularReflection = to_float3_s(0.0f);
    float3 vDiffuseReflection = to_float3_s(0.0f);
   
    float fAmbientOcclusion = GetAmbientOcclusion(ray, intersection, vNormal, iTime);
    float3 vAmbientLight = GetAmbientLight(vNormal) * fAmbientOcclusion;
   
    vDiffuseReflection += vAmbientLight;
   
    vSpecularReflection += cReflection * fAmbientOcclusion;
             
    #ifdef ENABLE_DIRECTIONAL_LIGHT
    float3 vLightDir = GetLightDirection();
      
    float fShadowBias = 0.05f;           
    float fShadowFactor = GetShadow( intersection.vPos + vLightDir * fShadowBias, vLightDir, 10.0f, iTime );
    float3 vIncidentLight = GetLightCol() * fShadowFactor;
   
    vDiffuseReflection += GetDiffuseIntensity( vLightDir, vNormal ) * vIncidentLight;                                                                               
    vSpecularReflection += GetBlinnPhongIntensity( ray, material, vLightDir, vNormal ) * vIncidentLight;
    #endif // ENABLE_DIRECTIONAL_LIGHT
   
    vDiffuseReflection *= material.cAlbedo;             
    
    #ifdef ENABLE_SPECULAR
    float fFresnel = Schlick(vNormal, ray.vDir, material.fR0, material.fSmoothness * 0.9f + 0.1f);
    cScene = _mix(vDiffuseReflection , vSpecularReflection, fFresnel);
    #else
    cScene = vDiffuseReflection;
    #endif
   
    return cScene;
}
 
__DEVICE__ float3 GetSceneColourSimple( const in C_Ray ray, float iTime, __TEXTURE2D__ iChannel0, __TEXTURE2D__ iChannel1 )
{
    C_HitInfo intersection;
    intersection = Raymarch(ray, intersection, 10.0f, 32, iTime);
                       
    float3 cScene;
 
    if(intersection.vObjectId.x < 0.5f)
    {
        cScene = GetSkyGradient(ray.vDir);
    }
    else
    {
        float3 vNormal = GetSceneNormal(intersection.vPos, iTime);
 
        C_Material material = GetObjectMaterial(intersection.vObjectId, intersection.vPos, vNormal, iChannel0, iChannel1);
 
        // use sky gradient instead of reflection
        float3 cReflection = GetSkyGradient(reflect(ray.vDir, vNormal));
 
        // apply lighting
        cScene = GetObjectLighting(ray, intersection, material, vNormal, cReflection, iTime );
    }
 
    ApplyAtmosphere(cScene, ray, intersection);
 
    return cScene;
}
 
__DEVICE__ float3 GetSceneColour( const in C_Ray ray, float iTime, __TEXTURE2D__ iChannel0, __TEXTURE2D__ iChannel1 )
{                                                         
    C_HitInfo intersection;
    intersection = Raymarch(ray, intersection, 30.0f, 256, iTime);
               
    float3 cScene;
     
    if(intersection.vObjectId.x < 0.5f)
    {
        cScene = GetSkyGradient(ray.vDir);
    }
    else
    {
        float3 vNormal = GetSceneNormal(intersection.vPos, iTime);
        C_Material material = GetObjectMaterial(intersection.vObjectId, intersection.vPos, vNormal, iChannel0, iChannel1);
 
        #ifdef ENABLE_MONTE_CARLO
        vNormal = normalize(vNormal + gRandomNormal / (5.0f + material.fSmoothness * 200.0f));
        #endif
 
        float3 cReflection;
        #ifdef ENABLE_REFLECTIONS   
        {
            // get colour from reflected ray
            float fSepration = 0.05f;
            C_Ray reflectRay;
            reflectRay.vDir = reflect(ray.vDir, vNormal);
            reflectRay.vOrigin = intersection.vPos + reflectRay.vDir * fSepration;
                                                                 
            cReflection = GetSceneColourSimple(reflectRay, iTime, iChannel0, iChannel1);                                                                       
        }
        #else
        cReflection = GetSkyGradient(reflect(ray.vDir, vNormal));                             
        #endif
        // apply lighting
        cScene = GetObjectLighting(ray, intersection, material, vNormal, cReflection, iTime );
    }
     
    ApplyAtmosphere(cScene, ray, intersection);
   
    return cScene;
}
 
__DEVICE__ void GetCameraRay( const in float3 vPos, const in float3 vForwards, const in float3 vWorldUp, const in float2 fragCoord, out C_Ray *ray, float2 iResolution)
{
    float2 vPixelCoord = fragCoord;
    #ifdef ENABLE_MONTE_CARLO
    vPixelCoord += swi2(gPixelRandom,z,w);
    #endif
    float2 vUV = ( vPixelCoord / iResolution );
    float2 vViewCoord = vUV * 2.0f - 1.0f;
 
    vViewCoord *= 0.75f;
     
    float fRatio = iResolution.x / iResolution.y;
 
    vViewCoord.y /= fRatio;                         
 
    (*ray).vOrigin = vPos;
 
    float3 vRight = normalize(cross(vForwards, vWorldUp));
    float3 vUp = cross(vRight, vForwards);
       
    (*ray).vDir = normalize( vRight * vViewCoord.x + vUp * vViewCoord.y + vForwards);       
}
 
__DEVICE__ void GetCameraRayLookat( const in float3 vPos, const in float3 vInterest, const in float2 fragCoord, out C_Ray *ray, float2 iResolution)
{
    float3 vForwards = normalize(vInterest - vPos);
    float3 vUp = to_float3(0.0f, 1.0f, 0.0f);
 
    GetCameraRay(vPos, vForwards, vUp, fragCoord, ray, iResolution);
}
 
__DEVICE__ float3 OrbitPoint( const in float fHeading, const in float fElevation )
{
    return to_float3(_sinf(fHeading) * _cosf(fElevation), _sinf(fElevation), _cosf(fHeading) * _cosf(fElevation));
}
 
__DEVICE__ float3 Gamma( const in float3 cCol )
{
    return sqrt_f3(cCol);
}
 
__DEVICE__ float3 InvGamma( const in float3 cCol )
{
    return cCol * cCol;
}
 
 
__DEVICE__ float3 Tonemap( const in float3 cCol )
{
    
    float3 vResult = to_float3_s(1.0f) - exp2_f3(-1.0f*cCol);

    return Gamma(vResult);
}
 
__DEVICE__ float3 InvTonemap( const in float3 cCol )
{
    float3 vResult = cCol;
    vResult = clamp(vResult, 0.01f, 0.99f);
    vResult = InvGamma(vResult);
    return  -1.0f * log2_f3(to_float3_s(1.0f) - vResult);
}
 
__KERNEL__ void TimewarpFuse(float4 fragColor, float2 fragCoord, float iTime, float2 iResolution, float4 iMouse, sampler2D iChannel0, sampler2D iChannel1)
{

    #ifdef ENABLE_MONTE_CARLO           
    CalcPixelRandom();
    #endif
     
    C_Ray ray;
     
    const float fCamreaHeadingMin = -0.8f;
    const float fCamreaHeadingMax = 1.8f;
    const float fCamreaElevationMin = 0.1f;
    const float fCamreaElevationMax = 0.7f;
    const float fCamreaDistMin = 3.0f;
    const float fCamreaDistMax = 2.0f;

    float2 vMouse = swi2(iMouse,x,y) / iResolution;
  
    // If we have never moved the mouse
    if(iMouse.x <= 0.0f)
    {
      swi2S(vMouse,x,y, to_float2(0.0f, 1.0f));
    }

float IIIIIIIIIIIIIIIIII;      
  
    float fHeading = _mix(fCamreaHeadingMin, fCamreaHeadingMax, vMouse.x);
    float fElevation = _mix(fCamreaElevationMin, fCamreaElevationMax, vMouse.y);
    float fCameraDist = _mix(fCamreaDistMax, fCamreaDistMin, vMouse.y);
   
    float3 vCameraPos = OrbitPoint(fHeading, fElevation) * fCameraDist;
   
    #ifdef ENABLE_MONTE_CARLO           
    float fDepthOfField = 0.025f;
    vCameraPos += gRandomNormal * fDepthOfField;
    #endif
     
    GetCameraRayLookat( vCameraPos, to_float3(0.0f, -0.5f, 0.2f), fragCoord, &ray, iResolution);
     
    float3 cScene = GetSceneColour( ray, iTime, iChannel0, iChannel1 ); 
      
    float fExposure = 0.4f;
    cScene = cScene * fExposure;

  // vignette
  float2 vUV = ((fragCoord / iResolution) - 0.5f) * 2.0f;
  float fDist = dot(vUV, vUV);
  fDist = fDist * fDist;
  float fAmount = 1.0f / (fDist * 5.0f + 1.0f);
  cScene = cScene * fAmount;

    #ifdef ENABLE_MONTE_CARLO                             
    float3 cPrev = swi3(_tex2DVecN(backbuffer,vUV.x,vUV.y,15),x,y,z);
    // add noise to pixel value (helps values converge)
    cPrev += (swi3(gPixelRandom,x,y,z) - 0.5f) * (1.0f / 255.0f);
    cPrev = InvTonemap(cPrev);
    // converge speed
    //float fBlend = 0.1f;
    float fBlend = 1.0f;
    float3 cFinal = _mix(cPrev, cScene, fBlend);
    #else
    float3 cFinal = cScene;
    #endif
   
    cFinal = Tonemap(cFinal);
         
    float fAlpha = 1.0f;
     
    fragColor = to_float4_aw( cFinal, fAlpha );
     
    SetFragmentShaderComputedColor(fragColor);
}

